variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
  
stages: 
  - build

build-release-win10-x64:
    variables:
      BUILD_FOLDER: build64
      BUILD_CONFIG: Release
    tags:
        - win10
    stage: build
    script:
        - cmake -B ${BUILD_FOLDER} -S .
        - cmake --build ${BUILD_FOLDER} --target SICKBEATBETTY_All --config ${BUILD_CONFIG}
        - cmake --build ${BUILD_FOLDER} --target installer --config ${BUILD_CONFIG}
    artifacts:
      paths:
        - ${BUILD_FOLDER}/Sick Beat Betty-*.msi
        - ${BUILD_FOLDER}/SICKBEATBETTY_artefacts/${BUILD_CONFIG}/VST3/Sick Beat Betty.vst3/
        - ${BUILD_FOLDER}/SICKBEATBETTY_artefacts/${BUILD_CONFIG}/Standalone/Sick Beat Betty.exe
      expire_in: 1 week


