variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 4
  
stages: 
  - build

build-win10-x64:
    tags:
        - win10
    stage: build
    script:
        - cmake -B build64 -S .
        - cmake --build build64 --target SICKBEATBETTY_All --config Release
        - cmake --build build64 --target installer --config Release


