name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload VST3
      uses: actions/upload-artifact@v3
      with:
        name: "Sick Beat Betty.vst3"
        path: build/SickBeatBetty_artefacts/Debug/VST3/

    - name: Upload Standalone
      uses: actions/upload-artifact@v3
      with:
        name: "Sick Beat Betty.exe"
        path: build/SickBeatBetty_artefacts/Debug/Standalone/

      
